### ISSUE TITLE
Audio desyncs from Video & Lyrics on some songs when using the "Skip to next lyrics" feature

### ISSUE THREAD

**Issue by Jatoxo** [UltraStar-Deluxe/Play#323] opened 2022-08-28 17:10 UTC
### Actual behaviour
When skipping to the next lyrics, the audio desyncs while lyrics and video stay synced
The audio appears to jump ahead too far

Demonstration:
https://user-images.githubusercontent.com/39669932/187086784-38fe2c93-923c-4c88-a38d-9a92b40b7dad.mp4

### Expected behaviour
Everything should stay in sync

### Steps to reproduce
1. Use the uploaded song TXT file
[Natural-1471.txt](https://github.com/UltraStar-Deluxe/Play/files/9440121/Natural-1471.txt)

2. Start the song and right-click to skip to the first lyrics

### Details
Provide some additional information:

- UltraStar Play version: 0.7.0
- Win 10 + 21H1 / 19043.1706

**Comment by achimmihca** [comment] 2022-08-31 18:51
### Summary
Unity has issues jumping to a new position in some mp3 files

### Workaround
Use ogg file instead or mp3 file with constant bit rate

### Details
- UltraStar Play tells Unity: Jump to position `11306 ms`
- Unity reports back the position in the song as `11306 ms`. Seems correct.
    - But Unity actually plays a different location, approx. 2 seconds further inside the song.

Thus, the lyrics and video are in sync with the position in the audio that is returned by Unity. But Unity actually plays a different part on this particular mp3.

- I did some tests with the audio file exported to mp3 using different parameters.
    - When using constant bit rate, Unity correctly jumps to the new position.
    - Thus, I assume Unity has an issue with variable bit rate mp3 files.

I will try to open a Unity bug report. But I don't think this will be an important issue for Unity, so I assume it may take some years before fix, if it will be fixed at all.

BTW: I was wrong, the txt file was not enough to reproduce this issue ;) . Thanks for the bug report and your help.

**Comment by achimmihca** [comment] 2022-09-28 15:29
> I will try to open a Unity bug report. 

Unity confirmed the bug. Looks like it is beeing worked on.

**Comment by achimmihca** [comment] 2023-07-09 11:01
Response from Unity:

> A fix for your bug report IN-15619: AudioClip's position change is inaccurate when using MP3 with variable bit rate has been verified and approved. Fix Version/s: 2023.2.0a23 Resolution Notes: MP3 Xing table of content decoding has been fixed to improve seeking accuracy.

**Comment by achimmihca** [comment] 2023-12-23 13:58
I can confirm that this seems to be fixed in Unity 2023.2.3f1.
At least my example project that I created to test the issue works fine now.

**Closed** 2024-06-23 13:18 UTC
Labels: bug
