### ISSUE TITLE
Lyrics helper: correct placement seems to be dependent on screen resolution

### ISSUE THREAD

**Issue by bohning** [UltraStar-Deluxe/Play#84] opened 2019-12-18 13:20 UTC
Issue type: Bug report

### Actual behaviour

The lyrics helper seems to be correctly placed for e.g. a game resolution of 800x600:
<img width="1680" alt="Bildschirmfoto 2019-12-18 um 14 16 09" src="https://user-images.githubusercontent.com/1497707/71089374-ffe67a00-21a0-11ea-9f3e-6ad55ad11280.png">

However, it seems to be incorrectly placed for e.g.  a game resolution of 2560x1600:
<img width="1680" alt="Bildschirmfoto 2019-12-18 um 14 11 13" src="https://user-images.githubusercontent.com/1497707/71089169-91a1b780-21a0-11ea-910c-53c5ad5fde71.png">

It is difficult to see this in the screenshots, but in the correct case, the lyrics helper is always exactly at the current syllable and never goes beyond the last syllable of a sentence, while in the incorrect case, it seems to be "stretched" and to start left of the actual lyrics and goes beyond the last syllable of the sentence (as is obvious in the second screenshot).

### Expected behaviour
The lyrics helper be placed correctly independent of game resolution.

### Steps to reproduce
Start UltraStar Play with different resolutions and observe the position of the lyrics helper.

### Details

Provide some additional information:

- UltraStar Play version: latest trunk
- Operating System + version: macOS 10.15.2

**Comment by achimmihca** [comment] 2020-01-22 21:45
Please check, whether the issue is fixed with the upcoming built of UltraStar Play.

**Comment by bohning** [comment] 2020-01-24 09:43
@achimmihca Issue solved, tested several different screen resolutions! Thanks a lot!

**Closed** 2020-01-25 16:03 UTC
Labels: bug
