### ISSUE TITLE
Text line is only half colored blue

### ISSUE THREAD

**Issue by Tirgatt** [UltraStar-Deluxe/Play#355] opened 2023-01-03 15:41 UTC
Issue type: Bug report

No matter which song I play, the line of text to be sung is not colored to match the text. About the first two words of the line are still colored correctly, but then it stops. The rest of the line is not colored. This applies to every newly displayed line of text. The error did not exist in version 0.7.0.

In addition, I can no longer play two songs by the artist "Ich + Ich". (worked on 0.7.0)

There is also a bug, which I hadn't tested with version 0.7.0, that the note for the second player (both singing the same vocals) is not filled, even though the points are counted correctly. Only the beginning of the note is minimally colored.

I have tested 0.8.0 on two different Windows (10 + 11) devices.

[UltraStar Play20230103.log](https://github.com/UltraStar-Deluxe/Play/files/10337822/UltraStar.Play20230103.log)
[Ich + Ich - Umarme Mich.txt](https://github.com/UltraStar-Deluxe/Play/files/10337823/Ich.%2B.Ich.-.Umarme.Mich.txt)

**Comment by achimmihca** [comment] 2023-01-03 16:26
duplicate of #352
These issues are fixed in the current master branch.

**Closed by achimmihca** 2023-01-03 16:26 UTC
