### ISSUE TITLE
Partial highscores are recorded

### ISSUE THREAD

**Issue by barbeque-squared** [UltraStar-Deluxe/Play#151] opened 2020-03-15 19:16 UTC
### Actual behaviour
Songs that have not been sung completely save highscores

### Expected behaviour
Only songs that have been sung completely save highscores

### Steps to reproduce
1. Start any song
2. At any point (this can even be before the first sentence!), Escape to cancel
3. A highscore with the partial score is recorded

Note: partial highscores are recorded even if the partial score itself is 0! I'm not sure if that's a different bug, or perhaps intended behaviour for completed songs, but a partial score of 0 should probably not ever get recorded.

### Details
Provide some additional information:

- UltraStar Play version: Linux build from (I'm assuming) March 15, 2020 ~11:16
- Operating System + version: Archlinux

**Comment by achimmihca** [comment] 2020-03-15 21:11
True. The issue is addressed in #152.
However, I argue that a final score of 0 is a valid highscore. In normal game play this will not occur, but even if it occurs it is not a problem (no crash or inconsistency).

**Comment by achimmihca** [comment] 2020-03-16 20:05
The branch has been merged. Please check if the issue has been fixed in the newest built.

**Closed** 2020-03-21 10:57 UTC
