### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by achimmihca** [UltraStar-Deluxe/Play#41] opened 2019-09-04 21:51 UTC
Issue type: Development discussion

In a collaborative project, it makes sense to decide on a code style, such that code from different people is more readable as it uses the same conventions.
I saw the [existing conventions of the project](https://github.com/UltraStar-Deluxe/Play/blob/master/CONTRIBUTING.md). However, in some points I don't concur and in others they are a little vague.

Unity C# guidelines differ a little from other C# styles, because Unity supports others languages as well and mixed styles (e.g. from JS). I found some blog posts with C# code guidelines with Unity in mind:
(a) https://github.com/raywenderlich/c-sharp-style-guide
(b) http://wiki.unity3d.com/index.php?title=Csharp_Coding_Guidelines&oldid=17000
They agree in many points.

(b) suggest to not prefix private members, enums, or classes. (a) also suggest to not prefix private members but is less strict with enums, and other classes. Both suggest to prefix interfaces with I.

Personally, I would like to use (a) (namely raywenderlich) as the basis for our new code style guidelines.
However, I think prefixing enums with E, and maybe abstract classes with A conveys information and is a good thing to do, similar to prefixing interfaces with I.
Furthermore, I would also want to prefix or suffix scenes, e.g., "SingScene", or "OptionScene" with corresponding scripts such as "SingSceneController". In this example, "Controller" would be the suffix for scripts related to a specific scene.

Prefixes for private members and static variables are discuraged in (a) and (b). Instead, they suggest camelCase for members (static or not) and PascalCase for constants, properties, methods, classes, namespaces, etc.
Thus, the only difference to our current style guide is to not use m_ and s_ prefixes for members.

Finally, our current style guide suggests "only strictly typed variables". Personally, I very much like type inference. IMO, reducing redundant type information makes code more readable. Note also that type inference is still strictly typed code. Note also that I am speaking of C#. Stuff like UnityScript should not be used for this project.
In C#, I often use the var keyword inside methods and when iterating over collections. From my experience, the type in most cases is trivial to infere from the right side (e.g. `var text = "hi";` or `var boxes = new List<Box>();` ), or the type does not matter anyway. Thus, I suggest to remove this rule and allow the var keyword of C# inside methods.

**Comment by achimmihca** [comment] 2019-09-04 21:53
I prepared the OmniSharp settings and an .editorconfig file to implement the new code style in vscode. So formatting will be done on save and the analyzer will report issues and improvements (e.g. naming violations or unused variables) directly in the editor.

**Comment by basisbit** [comment] 2019-09-04 22:38
Visual Studio and codacy static code analysis are also used in this project, so we should eventually change their cobfig files, too

**Comment by basisbit** [comment] 2019-09-04 22:44
Personally I don't understand in what circumstance var (not strictly typed variable definitions) would bring any advantages over generics or strictly typed code. If this project is successful, the code will be used for a long time. With having seen in bunch of projects how different people change code over time, I'd prefer not using loosely typed code if possible.
I am ok on all the other points you mentioned.

**Comment by achimmihca** [comment] 2019-09-05 14:11
Wheter type inference should be used or one should always write the type explicitly is for sure debateable. For instance there are discussions on [StackExchange](https://softwareengineering.stackexchange.com/a/257455).

The idea of this feature is to improve readability by avoiding redundant code, which might be needed for compilation but not for human understanding. This also tells you when you should or should not use it -- when the information is not redundant and relevant for the understanding then you should not use it.
From my experience, type information is not needed in many cases for the understanding, but takes a significant part of the line.

On the other side, I can also see that what is considered "relevant for the understanding" depends on the person. Furthermore, I can see that a rule "never use type inference" is easier to apply with consistency than "use type inference only when the type is redundant and irrelevant for the understanding" -- especially on projects with varying members.

So, if you prefer not to use var, then I can live with that. Do you prefer not to use var?

**Comment by basisbit** [comment] 2019-09-05 19:02
This is probably mostly a question of what you are used to and maybe a bit of a religion thing. From my personal experience, it is much easier to refactor complex code later on when there is only rather little amount of type inference. But then again, I mostly work with Java code.

Usually, when code is properly written from scratch, a good dev will make the code explain itself and nicely structure it (see [clean code cheat sheet](https://www.bbv.ch/images/bbv/pdf/downloads/V2_Clean_Code_V3.pdf)). Then, some other people add features, refactor stuff and suddenly, there is tons of complexity hidden in technical code which should not contain any complexity besides what would be needed for a purely functional programming style.

So, my question would be: Would you be ok and still continue participating in this project even if we make type declaration mandatory for variable declarations? (of course the types should be properly crafted/chosen and as generic as still feasible for the task. And generics are of course also allowed, where feasibly/helpful and not just extra complexity)

**Comment by achimmihca** [comment] 2019-09-05 19:48
As I said, I can live with that and I see your point.
So no "var" it is.

I will refactor my code with this style and then create a pull request.

**Comment by basisbit** [comment] 2019-09-05 20:02
Thank you! You'll get a couple of beers or whatever you like if we ever meet 😅

**Comment by achimmihca** [comment] 2019-10-17 14:42
Codacy: "Optional paremeters should not be used"
as a result `public void bla(string parameterWithDefault = "theDefault")` would not be allowed

Why is that? This can be quite handy.

**Comment by achimmihca** [comment] 2019-10-17 14:44
Codacy: "General exceptions should never be thrown"
as a result, `System.Exception` should not be thrown.

Why is that? What is our benefit from this rule?

**Comment by achimmihca** [comment] 2019-10-17 14:47
Codacy: "Methods and properties should be named in PascalCase"
Agreed. However, Unity itself violates this rule in certain cases, e.g. when using GUI instead Gui (`OnInspectorGUI`, `OnSceneGUI`)

Is it possible to ignore these special cases?

**Comment by basisbit** [comment] 2019-10-17 21:39
Hi there!
floating point object comparison: very often devs use the == / != operators wrong on floats. This rule exists to make it easier to maintain the codebase. When checking code changes, one can easily miss an incorrect comparison of floats. In the use case that you described, yes, != would be technically correct, but this can be done just as well by using for example the Doube.Equals method and that would also support the case that some code changed the value, then changed it back to almost the same value (for example because of serialization or whatever events). Anyways, the codacy checks are only suggestions. As a developer you can follow them, but you don't have to. Codacy doing the static code analysis just only a tool to support code review and to hint at code that should be checked.
Codacy supports ignoring certain warnings that already were reported, reviewed and a dev decided to click the ignore button.

readonly keyword: I'd consider this to be a bug in Unity, but after googling for this, I read that this is a design decision by Unity because they decided that one does not need to analyze static member objects. They probably did this to sanitize the amount of values which would show up in their inspector tool. When debugging using Visual Studio, this is not a problem. Anyways, Unity supports customization of the debug inspector tool, so that one could add readonly values to the unity-builtin debug tool. There already exist a bunch of almost ready to use code snippets for this - we should probably include one of them in the UltraStar Play project. Until this is done, feel free to either use readonly or not use it how you see fit. Please beware that code using readonly where values are supposed to stay read only are much more likely to be stable and just work for a long time. (see various Clean Code style guides and papers). If changing the unity editor to show readonly values turns out to be more of a problem, we can just disable the "readonyl check" rule in codacy.

General exceptions: General exceptions make it harder to figure out what the actual problem was. Occasionally, there will be bug reports that you can't reproduce or stacktraces that are hard to understand/debug. In these cases, you'll want to get an exception as precise as possible. If something goes wrong in UI code, you'll want to use a UnityException or similar (which makes handling it much easier). 
In a more complex application, the developer eventually has to implement proper exception handling. When the code only throws SystemExceptions or ApplicationExceptions, then you try to implement exception handling, you'll probably catch way too many exception cases because you can't filter them properly - for some of them your handling code will not fit properly. When using only Exception, this task pretty much gets impossible to do. You can't decide any more if the exception should or even can be logged, and if the exception should be hidden from the user or displayed as a Error/Warning/Info message. Thus, if possible, throw a fitting exception type and implement exception handling dependent on exception type. If You there exists no fitting exception type, just create a new one.

Unity vs. PascalCase: ... I'll have to look into a) disabling the rule which checks this, b) just ignoring the occurrences where it is clearly caused by Unity, or adjusting the rule to not match on certain key words like On*GUI

optional: I agree on that. I'll remove that rule.

Yes, it is possibly to make Codacy ignore certain files or folders + subfolders. I'll check how to do this any change the config accordingly. Thank you for pointing this out.

**Comment by basisbit** [comment] 2019-11-28 23:51
I'll close this issue for now, if there are any more suggestions for changing codacy rule checks or for changing the general code style best practices of this project, please feel free to reopen this issue.

**Closed by basisbit** 2019-11-28 23:51 UTC
