### ISSUE TITLE
Split stereo microphone channel (Singstarr Wireless) 

### ISSUE THREAD

**Issue by 10bn** [UltraStar-Deluxe/Play#257] opened 2021-10-25 08:59 UTC
Issue type: Feature request

### Actual behaviour

My 2 Singstarr wireless microphones are connected via a usb bridge which exposes them as one stereo device. 

### Expected behaviour

On the normal Ultra Star Deluxe it is possible to assign channel 1 & 2 of a stereo device to individual users. I would appreciate to see this feature also in USDP.

**Comment by ZerNico** [comment] 2021-11-10 21:48
> Thanks for the fast response. I'm currently trying to solve the issue on system level utilizing virtual audio devices. Do you or someone else can recommend any software that could be of help doin this?

I suppose Voicemeeter would be able to do that.

**Comment by achimmihca** [comment] 2022-02-26 09:00
I close this as duplicate of #85

@jaddel , if you found a workaround using other tools, please add a comment on #85, or (even better) in the [wiki](https://github.com/UltraStar-Deluxe/Play/wiki/Audio-Configuration)

**Closed as completed by achimmihca** 2022-02-26 09:00 UTC
