### ISSUE TITLE
Multi Microphone Support for Linux

### ISSUE THREAD

**Issue by paradigmn** [UltraStar-Deluxe/Play#275] opened 2022-01-31 21:01 UTC
Issue type: Bug report

### Actual behaviour
Only one microphone is recording in the Sing scene if multiple wired mics are connected (USB/analog) and assigned to the individual players. All microphones working individually in single player mode. Additionally, a player using the Companion app can sing alongside the one recording USB/analog microphone.

In Short:
- 2x wired mics : only one device recording
- 1x wired mic + 1x Companion app: both devices recording as desired

### Expected behaviour
All microphones should record properly.

### Steps to reproduce
1. Open the Ultrastar Play on Linux
2. Select two or more USB/analog mics for singing
3. Enable two or more players
4. Select song to sing
5. Assign players to mics
6. Start singing

### Details
Provide some additional information:

- UltraStar Play version: latest main
- Operating System + version: Debian 12
- This issue appears to be Linux specific as everything works fine on Windows
- The log shows both devices started recording (the second one is the mic which is able to record in the end)
- if applicable, add a log file: 

```
Starting recording with 'Sony SingStar USBMIC Analog Stereo' at 44100 Hz
UnityEngine.Debug:Log (object)
MicSampleRecorder:StartRecording () (at Assets/Common/Audio/Recording/MicSampleRecorder.cs:94)
PlayerPitchTracker:Start () (at Assets/Scenes/Sing/PlayerController/PlayerPitchTracker.cs:83)

Starting recording with 'Headset [PC 8] Mono' at 44100 Hz
UnityEngine.Debug:Log (object)
MicSampleRecorder:StartRecording () (at Assets/Common/Audio/Recording/MicSampleRecorder.cs:94)
PlayerPitchTracker:Start () (at Assets/Scenes/Sing/PlayerController/PlayerPitchTracker.cs:83)
```

**Comment by achimmihca** [comment] 2022-02-01 08:44
Thanks for the detailed bug report.

I could imagine Linux drivers to be an issue here.
Is there some other software on Linux where you can record with multiple mics at the same time?

**Comment by basisbit** [comment] 2022-02-01 09:40
Also, could someone test if having multiple microphones on multiple soundcards works, and test with alsa and with pulseaudio? Taking a look at the Unity framework forums regarding this and opening a bug report there might also help.

**Comment by basisbit** [comment] 2022-02-01 09:42
> I could imagine Linux drivers to be an issue here. Is there some other software on Linux where you can record with multiple mics at the same time?

Yes, UltraStar Deluxe for example.

**Comment by paradigmn** [comment] 2022-02-01 10:50
> > I could imagine Linux drivers to be an issue here. Is there some other software on Linux where you can record with multiple mics at the same time?
> 
> Yes, UltraStar Deluxe for example.

Yes, USDX work perfectly fine on Linux. Im currently using Pipewire as sound server, however I think Pulsaudio showed the same behavior a while ago. I will try to setup a test installation with a stable distro for evaluating different configurations. At this point i am not sure how to use alsa as default without an audio server on top.

**Comment by paradigmn** [comment] 2022-02-03 13:28
I freshly installed a PC with Debian 11 + Pulseaudio. The results are basically the same. Additionally, i tried two analog mics with onboard sound and a PCI soundcard. Only one mic is able to record in multi player mode. I wasn't able to use ALSA only as the desktop environment is coupled to pulseaudio. Hence, neither stopping the service nor uninstalling Pulse was doable. Is it even possible to run a modern Linux desktop without an audio server on top?

**Comment by basisbit** [comment] 2022-02-06 18:35
I don't think any more testing will help. Instead, there are probably two ways to continue:
- USPlay only uses the API form Unity. If that has issues on Linux, contact Unity so they fix their software. Thus, someone please report this problem in the Unity issue tracker.
- Another or an additional option could be to implement audio-input using for example [PortAudio](https://github.com/PortAudio/portaudio) or similar cross-platform library to be able to get additional audio input sources. This could also be used to add support for multi-channel audio input cards.

**Comment by hoehermann** [comment] 2022-09-16 20:43
> Also, could someone test if having multiple microphones on multiple soundcards works, and test with alsa and with pulseaudio?

I have a hard time building USDX on Ubuntu 22.04, that is why I want to give Play 0.7.0 a shot.

Unity seems to use FMOD as their audio back-end. FMOD does a really nice job abstracting the underlying system. **It does not make any difference whether you use PulseAudio or alsa**. In both cases, only the device is considered, not the channels. FMOD always records from all channels and does a downmix. As it stands, you need one device per microphone.

Unfortunately, only one of the selected devices are actually used for pitch detection. It looks like it is the first one by device name, but I am not sure. This feels like a bug since we can definitely select multiple sources in the Recording screen.

> Is it even possible to run a modern Linux desktop without an audio server on top?

Yes, but it is rather cumbersome and I cannot recommend it these days.

Side-note: As it is good Linux tradition, alsa device names are a mess and a drop-down control instead of the left-right switcher would really help. Since using alsa offers no benefits and most desktops are using PulseAudio nowadays, I do not think this is much of a problem.

> At this point i am not sure how to use alsa as default without an audio server on top.

You do not need to. For the kind of shenanigans we are doing with USDX, you can tell PulseAudio to create virtual alsa cards as needed via `~/.asoundrc`. Unity's FMOD seems to support PulseAudio directly, so that is no option for Play.

**Comment by achimmihca** [comment] 2023-01-06 10:18
duplicate of #85

**Closed by achimmihca** 2023-01-06 10:18 UTC
Labels: enhancement
